/********************************************************************
* DictOutput.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DictOutput.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictOutput();
extern void G__cpp_setup_inheritanceDictOutput();
extern void G__cpp_setup_typetableDictOutput();
extern void G__cpp_setup_memvarDictOutput();
extern void G__cpp_setup_globalDictOutput();
extern void G__cpp_setup_memfuncDictOutput();
extern void G__cpp_setup_funcDictOutput();
extern void G__set_cpp_environmentDictOutput();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TA2CBKinematicFitter.h"
#include "TA2KFParticle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictOutputLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictOutputLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DictOutputLN_TMatrixTSparseDiaglEfloatgR;

/* STUB derived class for protected member access */
